name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 16.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: yarn install
      - name: lint
        run: yarn run lint
      - name: build
        run: yarn run build
