name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 16.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: v1-node-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('yarn.lock') }}
      - name: install dependencies
        run: yarn install
      - name: eslint
        run: yarn run lint
      - name: build
        run: yarn run build
